// Textos de la interfaz (español por defecto)

export const strings = {
  appName: 'Plutxus',
  chat: {
    emptyStateTitle: '¿En qué puedo ayudarte hoy?',
    inputPlaceholder: 'Escribe tu mensaje...',
    generating: 'Generando...',
    newChat: 'Nuevo chat',
    selectModel: 'Selecciona un modelo',
    noModelSelected: 'Sin modelo',
    noModelDownloaded: 'No tienes modelos descargados. Ve a Modelos para descargar uno.',
  },
  sidebar: {
    models: 'Modelos',
    projects: 'Proyectos',
    chats: 'Chats',
    rename: 'Renombrar',
    delete: 'Eliminar',
    settings: 'Ajustes',
  },
  settings: {
    title: 'Ajustes',
    appearance: 'Apariencia',
    light: 'Claro',
    dark: 'Oscuro',
    auto: 'Auto',
    language: 'Idioma',
    system: 'Sistema',
    spanish: 'Español',
    more: 'Más',
    aboutYou: 'Sobre Ti',
    aboutYouSubtitle: 'Personaliza tu IA',
    nickname: 'Nombre o Apodo',
    occupation: '¿A qué te dedicas?',
    passions: 'Tus pasiones',
    models: 'Modelos',
    apiKeys: 'API Keys',
    apiKeysComingSoon: 'Próximamente: conecta tu propia API key.',
    meetCreator: 'Conoce al Creador',
    supportProject: 'Apoya el proyecto',
    rateApp: 'Califica la app',
  },
  models: {
    title: 'Biblioteca de Modelos',
    download: 'Descargar',
    pause: 'Pausar',
    resume: 'Reanudar',
    delete: 'Eliminar',
    active: 'Activo',
    setActive: 'Usar este modelo',
    context: 'Contexto',
    vision: 'Visión',
    size: 'Tamaño',
    notEnoughSpace: 'No hay suficiente espacio en disco para este modelo.',
  },
};
